from turtle import*
fontsize= int(input("ingrese el tamano de la letra"))
scala=1.2
cuadrante=fontsize*scala
def graf_tricky(cuadrante):
    speed(11)
    penup()
    pensize(4)
    fd(cuadrante)
    left (90)
    pendown()
    fd(cuadrante*3)
    penup()
    right(180)
    fd(cuadrante*3)
    penup()
    left(90)
    fd(cuadrante)
    pendown()
    left(90)
    fd(cuadrante*3)
    penup()
    left(180)
    fd(cuadrante)
    left(90)
    fd(cuadrante)
    left(180)
    pendown()
    fd(cuadrante*3)
    penup()
    left(90)
    fd(cuadrante)
    left(90)
    pendown()
    fd(cuadrante*3)
    penup()
    goto(0,0)
