from turtle import*
fontsize= 100
scala=1.2
cuadrante=fontsize*1.2
def graf_tricky(cuadrante):
    speed(11)
    penup()
    pensize(4)
    fd(cuadrante)
    left (90)
    pendown()
    fd(cuadrante*3)
    penup()
    right(180)
    fd(cuadrante*3)
    penup()
    left(90)
    fd(cuadrante)
    pendown()
    left(90)
    fd(cuadrante*3)
    penup()
    left(180)
    fd(cuadrante)
    left(90)
    fd(cuadrante)
    left(180)
    pendown()
    fd(cuadrante*3)
    penup()
    left(90)
    fd(cuadrante)
    left(90)
    pendown()
    fd(cuadrante*3)
    penup()
    goto(0,0)
##    goto(-150,-100)
##    pendown()
##    write("player 1= ", font=('Arial',30,'normal'))
##    penup()
##    goto(-150,-150)
##    pendown()
##    write("player 2= ", font=('Arial',30,'normal'))
